<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.eclipse.ee4j</groupId>
        <artifactId>project</artifactId>
        <version>2.0.2</version>
        <relativePath/>
    </parent>

    <groupId>jakarta.agentic-ai</groupId>
    <artifactId>jakarta.agentic-ai-parent</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>Jakarta Agentic AI Parent</name>
    <description>Parent build for Jakarta Agentic AI modules.</description>
    <url>https://github.com/jakartaee/agentic-ai</url>

    <modules>
        <module>api</module>
        <module>spec</module>
        <module>tck</module>
        <module>examples</module>
    </modules>

    <licenses>
        <license>
            <name>Eclipse Foundation Specification License (EFSL)</name>
            <url>https://www.eclipse.org/legal/efsl.php</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <scm>
        <connection>scm:git:git://github.com/jakartaee/agentic-ai.git</connection>
        <developerConnection>scm:git:ssh://git@github.com/jakartaee/agentic-ai.git</developerConnection>
        <url>https://github.com/jakartaee/agentic-ai</url>
    </scm>

    <issueManagement>
        <system>GitHub</system>
        <url>https://github.com/jakartaee/agentic-ai/issues</url>
    </issueManagement>

    <developers>
        <developer>
            <name>Jakarta Agentic AI Developers</name>
            <email>agentic-ai-dev@eclipse.org</email>
            <organization>Eclipse Foundation</organization>
            <organizationUrl>https://www.eclipse.org</organizationUrl>
        </developer>
    </developers>

    <distributionManagement>
        <snapshotRepository>
            <id>payara-nexus-snapshots</id>
            <url>https://nexus.dev.payara.fish/repository/payara-snapshots/</url>
        </snapshotRepository>
    </distributionManagement>

    <properties>
        <maven.compiler.release>17</maven.compiler.release>
        <spec.version>1.0</spec.version>
        <!-- set to false for release -->
        <spec.nonFinal>true</spec.nonFinal>
        <!-- Draft | Final Release -->
        <spec.status>Draft</spec.status>
        <nexus.staging.repository>agentic-ai-staging</nexus.staging.repository>
        <project.build.outputTimestamp>2026-04-12T00:00:00Z</project.build.outputTimestamp>
    </properties>
</project>
